# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B6S4abmyqV08vmm8ztgBzA2euZ_51dqc
"""

from flask import Flask, request, render_template
import json, time, requests

headers = {
    "Authorization": "Token r8_Y9am1vAuvupcDY0OdNXOdzhOgNIzzcc3G5ddx",
    "Content Type": "application/json"
}
app = Flask(__name__)
@app.route("/",methods=['GET','POST'])
#app.route is a decorator
def index():
    if request.method=='POST':
        q = request.form.get("q")
        print(q)
        body = json.dumps(
            {
                "version": "db21e45d3f7023abc2a46ee38a23973f6dce16bb082a930b0c49861f96d1e5bf",
                "input": {"prompt": q}
            }
        )
        output = requests.post("https://api.replicate.com/vi/predictions", data=body, headers = headers)
        time.sleep(10)
        get_url = output.json()["urls"]["get"]
        get_result = requests.post(get_url, headers=headers).json()["output"]
        return (render_template("index.html", result=get_result[0]))
    else:
        return (render_template('index.html',result="waiting for question...."))
if __name__ == "__main__":
    app.run()